config/routes.rb
Rails.application.routes.draw do
  post 'auth_user' => 'authentication#authenticate_user'
  post 'reg_user' => 'authentication#register_user'
  get 'home' => 'home#index'
  get 'conversations/index' => 'conversations#index'
  post 'conversations/create' => 'conversations#create'
  get 'messages/index' => 'messages#index'
  post 'messages/create' => 'messages#create'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
    belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :recipient_id

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR
     (conversations.sender_id = ? AND conversations.recipient_id =?)", 
     sender_id,recipient_id, recipient_id, sender_id)
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   attr_reader :current_user

  protected
  def authenticate_request!
    unless user_id_in_token?
      render json: { errors: ['Not Authenticated'] }, status: :unauthorized
      return
    end
    @current_user = User.find(auth_token[:user_id])
  rescue JWT::VerificationError, JWT::DecodeError
    render json: { errors: ['Not Authenticated'] }, status: :unauthorized
  end

  private
  def http_token
      @http_token ||= if request.headers['Authorization'].present?
        request.headers['Authorization'].split(' ').last
      end
  end

  def auth_token
    @auth_token ||= JsonWebToken.decode(http_token)
  end

  def user_id_in_token?
    http_token && auth_token && auth_token[:user_id].to_i
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def authenticate_user
    user = User.find_for_database_authentication(email: params[:email])
    if user.valid_password?(params[:password])
      render json: payload(user)
    else
      render json: {errors: ['Invalid Username/Password']}, status: :unauthorized
    end
  end

  def register_user
    user = User.create(email: params[:email], password: params[:password])
    if user.id == nil
      render json: {errors: ['Missing Info or User exists']}, status: :unauthorized
    else
      render json: '{user created}'
    end
  end
  
  private

  def payload(user)
    return nil unless user and user.id
    {
      auth_token: JsonWebToken.encode({user_id: user.id}),
      user: {id: user.id, email: user.email}
    }
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_request!

  def index
    @users = User.all
    render json: @users
  end

  def create
    sender_id = current_user.id
    recipient_id = User.where(email:params[:recipient_email])[0][:id]
    if Conversation.between(sender_id,recipient_id).present?
      @conversation = Conversation.between(sender_id, recipient_id).first
    else
      @conversation = Conversation.create!(sender_id: sender_id, recipient_id: recipient_id)
    end
    render json: "{\"conversation_id\":#{@conversation.id}}"
    #redirect_to conversation_messages_path(@conversation)
  end
  

private
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_request!

  def index
    render json: {'logged_in' => true}
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_request!
  before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    @messages = @conversation.messages
    
    if @messages.last
      if @messages.last.user_id != current_user.id
        @messages.last.read = true;
      end
    end
    render json: @messages

  end
  def new
    @message = @conversation.messages.new
  end
#create a message, if message is created a message will display indicating that the message was created
  def create
    @message = @conversation.messages.new(user_id: current_user.id, body: params[:body], conversation_id: params[:conversation_id])
    if @message.save
      #redirect_to conversation_messages_path(@conversation)
      render json: "{message created}"
    end
  end

private
  def message_params
    params.require(:message).permit(:body, :user_id)
  end
end

app/controllers/messages_controllers.rb
class MessagesController < ApplicationController
  before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    #@messages = @conversation.messages
    #if @messages.length > 10
     # @over_ten = true
      #@messages = @messages[-10..-1]
    #end
    #if params[:m]
     # @over_ten = false
      #@messages = @conversation.messages
    #end
    if @messages.last
      if @messages.last.user_id != current_user.id
        @messages.last.read = true;
      end
    end

    @message = @conversation.messages.new
  end

  def new
    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)
    if @message.save
      redirect_to conversation_messages_path(@conversation)
    end
  end

private
  def message_params
    params.require(:message).permit(:body, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conversations/index.html.erb
<div class="ui segment">
  <h3>Mailbox</h3>

  <div class="ui list">
    <div class="item">
      <% @conversations.each do |conversation| %>
        <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
          <% if conversation.sender_id == current_user.id %>
            <% recipient = User.find(conversation.recipient_id) %>
          <% else %>
            <% recipient = User.find(conversation.sender_id) %>
          <% end %>
          <%= link_to recipient.first_name, conversation_messages_path(conversation)%>
        <% end %>
      <% end %>
    </div>
  </div>
</div>


<div class="ui segment">
  <h3>All Users</h3>
  <div class="ui list">
    <% @users.each do |user| %>
      <% if user.id != current_user.id %>
      <div class="item">
        <%= user.first_name %> <%= link_to 'Message me!', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FSchat</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="ui grid">
    <div class="row">
      <div class="fourteen wide centered column">
        <h2 class="ui header">
          <i class="mail icon"></i>
          <div class="content">
            Simple Messaging App
          </div>
        </h2>
        <div class="ui purple inverted menu">
          <i class="home icon"></i><%= link_to "Home", root_path, class: "item" %>
            <% if current_user %>
              <%= link_to "Mailbox", conversations_path, class: "item" %>
              <div class="right menu">
                <%= link_to 'Sign Out', signout_path, class: "item" %>
              </div>
            <% else %>
              <div class="right menu">
                <%= link_to 'Sign Up', signup_path, class: "item" %>
                <%= link_to "Sign-In", signin_path, class: "item" %>
              </div>
            <% end %>
        </div>

        <%= yield %>
      </div>
    </div>
  </div>



</body>
</html>